/**
 * Cloudflare Stream video registry and helpers.
 * Customer subdomain: customer-8w5s9dekjdinwesc.cloudflarestream.com
 *
 * All videos configured for: autoplay, loop, muted (hero background pattern).
 * Posters generated by Cloudflare Stream at configured timestamps.
 */

const STREAM = "customer-8w5s9dekjdinwesc.cloudflarestream.com";

export const streamVideos = {
  home: {
    uid: "2baff6ee682afbfae617fd25ed2b0209",
    title: "Forestal MT | Exporting Nature Without Borders",
    duration: 22.9,
    posterPct: 0.3,
  },
  batanaOil: {
    uid: "709312413ff576260a7596e37d4d5c97",
    title: "Batana Oil | Ancestral Miskito Elixir",
    duration: 21.7,
    posterPct: 0.25,
  },
  stinglessBeeHoney: {
    uid: "d26fac9cccc86e666b136d952c1ea413",
    title: "Stingless Bee Honey | The Maya Heritage",
    duration: 21.8,
    posterPct: 0.35,
  },
  traditionalHerbs: {
    uid: "7dc57c8cc048bb7a7ac5e5f2aefb1eb0",
    title: "Traditional Herbs | Sacred Wisdom Rooted in Nature",
    duration: 20.0,
    posterPct: 0.3,
  },
} as const;

export type StreamVideoKey = keyof typeof streamVideos;

// ---------------------------------------------------------------------------
// Stream URL builders
// ---------------------------------------------------------------------------

/** Iframe embed URL with autoplay, loop, muted (hero background video). */
export function getStreamIframe(uid: string): string {
  return `https://${STREAM}/${uid}/iframe?autoplay=true&loop=true&muted=true&controls=false&preload=auto`;
}

/** HLS manifest for custom <video> players. */
export function getStreamHls(uid: string): string {
  return `https://${STREAM}/${uid}/manifest/video.m3u8`;
}

/**
 * Static poster image at the configured timestamp.
 * Cloudflare generates this server-side — no local processing needed.
 * @param width  - poster width (default 1920)
 * @param height - poster height (default 1080)
 * @param fit    - crop strategy (default "crop")
 */
export function getStreamPoster(
  uid: string,
  width = 1920,
  height = 1080,
  fit: "crop" | "clip" | "scale" | "fill" = "crop",
): string {
  return `https://${STREAM}/${uid}/thumbnails/thumbnail.jpg?width=${width}&height=${height}&fit=${fit}`;
}

/**
 * Animated GIF thumbnail (preview on hover).
 * Cloudflare generates a short animated clip server-side.
 * @param duration - seconds of animation (default 4)
 * @param width    - gif width (default 480)
 * @param fps      - frames per second (default 8)
 */
export function getStreamAnimatedThumb(uid: string, duration = 4, width = 480, fps = 8): string {
  return `https://${STREAM}/${uid}/thumbnails/thumbnail.gif?duration=${duration}s&width=${width}&fps=${fps}`;
}

/**
 * Thumbnail at a specific timestamp.
 * Useful for video chapter markers or storyboard grids.
 */
export function getStreamThumbAt(
  uid: string,
  timeSeconds: number,
  width = 320,
  height = 180,
): string {
  return `https://${STREAM}/${uid}/thumbnails/thumbnail.jpg?time=${timeSeconds}s&width=${width}&height=${height}&fit=crop`;
}

// ---------------------------------------------------------------------------
// <video> tag attributes for hero background videos
// ---------------------------------------------------------------------------

/** MP4 download URL — requires "Allow Downloads" enabled per video in CF Stream dashboard. */
export function getStreamMp4(uid: string): string {
  return `https://${STREAM}/${uid}/downloads/default.mp4`;
}

/** HTML attributes for autoplay background video. */
export const heroVideoAttrs = {
  autoplay: true,
  loop: true,
  muted: true,
  playsinline: true,
  preload: "metadata" as const,
  disablePictureInPicture: true,
} as const;
